# Generated by Django 6.0 on 2025-12-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cve",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("raw_json", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
    ]
