# Generated by Django 6.0 on 2025-12-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stopple_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Syncer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sync_index", models.IntegerField()),
            ],
        ),
    ]
